
name: Bank Frontend Pipeline

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - cicd

jobs:
  Continues-Integration_build_and_push:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build container image
      run: docker build -t bank-app-frontend:latest .

    - name: Log in to ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 029373387388.dkr.ecr.us-east-1.amazonaws.com
  
    - name: Tag Docker image
      run: docker tag bank-app-frontend:latest 029373387388.dkr.ecr.us-east-1.amazonaws.com/bank-frontend:${{ github.run_number }}
    
    - name: Push image to ECR
      run: docker push 029373387388.dkr.ecr.us-east-1.amazonaws.com/bank-frontend:${{ github.run_number }}


    - name: Clean up Docker image locally
      run: |
        docker rmi bank-app-frontend:latest
        docker rmi 029373387388.dkr.ecr.us-east-1.amazonaws.com/bank-frontend:${{ github.run_number }}

    - name: Clean up GitHub repo on runner
      run: rm -rf ./*


  
  Continues-Update_k8s_manifest:
    runs-on: self-hosted
    needs: Continues-Integration_build_and_push
    steps:
    - name: Checkout repository.
      env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
      run: |
         git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/kaluifekwe/kubernetes-manifest-bank_app.git
         
         cd kubernetes-manifest-bank_app
         git config --global user.email "support@digitalwitchng.online"
         git config --global user.name "kaluifekwe"

         sed -i "s+029373387388.dkr.ecr.us-east-1.amazonaws.com/bank-frontend:.*+029373387388.dkr.ecr.us-east-1.amazonaws.com/bank-frontend:${{ github.run_number }}+g" ./bank-project/frontend.yaml

         cat ./bank-project/frontend.yaml | grep -q "029373387388.dkr.ecr.us-east-1.amazonaws.com/bank-frontend:${{ github.run_number }}"

         git add bank-project/frontend.yaml
         git commit -m "Update frontend image to version ${{ github.run_number }}"
         git push origin main
